### ISSUE TITLE
Stretch goal: server-side input sanitisation

### ISSUE THREAD

**Issue by VirtualDOMinic** [fac-14/NDJS-node-autocompleter#14]
After URI decoded, we want to use regex (similar to last week) to remove misc/weird characters that could be used to inject code on the server/mess up our emboldening regex ( issue #12 )!

**Comment by VirtualDOMinic** [comment]
@dupreesi is currently working on this

**Comment by dupreesi** [comment]
![bildschirmfoto 2018-07-26 um 16 07 15](https://user-images.githubusercontent.com/23721486/43271003-50765340-90ee-11e8-84e5-0bcc5101846c.png)
![bildschirmfoto 2018-07-26 um 16 09 03](https://user-images.githubusercontent.com/23721486/43271006-520d7d0a-90ee-11e8-8a83-1ad4578c9652.png)

Is that modification what you were after?

**Comment by VirtualDOMinic** [comment]
@dupreesi not quite, sadly! The above is client-side and is  "messing" with the URI encoding, which we want to avoid. Will chat in gitter then summarise here
